import type { GlobalThemeOverrides } from 'naive-ui/es/config-provider';
import type { ThemeColorTokens } from '@/stores/settings.store';

export function buildThemeOverrides(colors: ThemeColorTokens): GlobalThemeOverrides {
  const {
    background,
    border,
    borderStrong,
    danger,
    faint,
    muted,
    panel,
    panelMuted,
    primary,
    primaryBorder,
    primaryHover,
    primaryPressed,
    scrollbar,
    scrollbarHover,
    shadowFloating: shadow,
    success,
    surface,
    surfaceActive,
    surfaceHover,
    text,
    textSoft,
    warning,
  } = colors;

  return {
    common: {
      primaryColor: primary,
      primaryColorHover: primaryHover,
      primaryColorPressed: primaryPressed,
      primaryColorSuppl: primary,
      infoColor: primary,
      infoColorHover: primaryHover,
      infoColorPressed: primaryPressed,
      infoColorSuppl: primary,
      successColor: success,
      warningColor: warning,
      errorColor: danger,
      textColorBase: text,
      textColor1: text,
      textColor2: textSoft,
      textColor3: muted,
      textColorDisabled: faint,
      placeholderColor: muted,
      placeholderColorDisabled: faint,
      iconColor: muted,
      iconColorHover: textSoft,
      iconColorPressed: text,
      iconColorDisabled: faint,
      dividerColor: border,
      borderColor: border,
      closeIconColor: muted,
      closeIconColorHover: textSoft,
      closeIconColorPressed: text,
      closeColorHover: surfaceHover,
      closeColorPressed: surfaceActive,
      clearColor: muted,
      clearColorHover: textSoft,
      clearColorPressed: text,
      scrollbarColor: scrollbar,
      scrollbarColorHover: scrollbarHover,
      progressRailColor: surfaceActive,
      railColor: surfaceActive,
      popoverColor: panel,
      tableColor: panel,
      cardColor: panel,
      modalColor: panel,
      bodyColor: background,
      inputColor: panel,
      codeColor: surface,
      tabColor: panelMuted,
      actionColor: surface,
      tableHeaderColor: panelMuted,
      hoverColor: surfaceHover,
      tableColorHover: surfaceHover,
      tableColorStriped: panelMuted,
      pressedColor: surfaceActive,
      inputColorDisabled: surface,
      buttonColor2: surface,
      buttonColor2Hover: surfaceHover,
      buttonColor2Pressed: surfaceActive,
      boxShadow1: shadow,
      boxShadow2: shadow,
      boxShadow3: shadow,
    },
    Button: {
      borderRadiusSmall: '5px',
    },
    Input: {
      heightTiny: '24px',
      heightSmall: '30px',
      heightMedium: '30px',
      heightLarge: '36px',
      fontSizeTiny: '11px',
      fontSizeSmall: '12px',
      fontSizeMedium: '12px',
      fontSizeLarge: '14px',
      borderRadius: '5px',
      textColor: text,
      textColorDisabled: textSoft,
      textDecorationColor: text,
      caretColor: primary,
      placeholderColor: muted,
      placeholderColorDisabled: faint,
      color: panel,
      colorDisabled: surface,
      colorFocus: panel,
      border: `1px solid ${border}`,
      borderDisabled: `1px solid ${border}`,
      borderHover: `1px solid ${borderStrong}`,
      borderFocus: `1px solid ${primaryBorder}`,
      boxShadowFocus: `inset 0 0 0 1px ${primaryBorder}`,
      iconColor: muted,
      iconColorDisabled: faint,
      iconColorHover: textSoft,
      iconColorPressed: text,
      clearColor: muted,
      clearColorHover: textSoft,
      clearColorPressed: text,
      suffixTextColor: textSoft,
    },
    Message: {
      color: panel,
      colorInfo: panel,
      colorSuccess: panel,
      colorWarning: panel,
      colorError: panel,
      colorLoading: panel,
      textColor: text,
      textColorInfo: text,
      textColorSuccess: text,
      textColorWarning: text,
      textColorError: danger,
      textColorLoading: text,
      iconColorError: danger,
      boxShadow: `${shadow}, inset 0 0 0 1px ${border}`,
      boxShadowInfo: `${shadow}, inset 0 0 0 1px ${border}`,
      boxShadowSuccess: `${shadow}, inset 0 0 0 1px ${border}`,
      boxShadowWarning: `${shadow}, inset 0 0 0 1px ${border}`,
      boxShadowError: `${shadow}, inset 0 0 0 1px ${border}`,
      boxShadowLoading: `${shadow}, inset 0 0 0 1px ${border}`,
      closeColorHover: surfaceHover,
      closeColorHoverError: surfaceHover,
      closeColorPressed: surfaceActive,
      closeColorPressedError: surfaceActive,
      border: '0',
    },
    Switch: {
      railColorActive: primary,
    },
  };
}
