/// Fields the system editor renders as structured controls; every other key
/// in a `.system` spec is treated as an extra passthrough field.
export const SYSTEM_STRUCTURED_FIELD_KEYS: ReadonlySet<string> = new Set([
  'id',
  'type',
  'aiType',
  'statsScript',
  'aiScript',
  'runScriptWhilePaused',
  'runScriptWhileIdle',
  'blockActionsWhileChargingDown',
  'canNotCauseOverload',
  'canUseWhileRightClickSystemOn',
  'clampTurnRateAfter',
  'clampMaxSpeedAfter',
  'alwaysAccelerate',
  'flameoutOnImpactChance',
  'fadeActivationSoundOnChargedown',
  'activatingShieldsCancels',
  'useSound',
  'loopSound',
  'deactivateSound',
  'outOfUsesSound',
  'soundFilterType',
  'soundFilterGain',
  'soundFilterGainHF',
  'engineGlowColor',
  'engineGlowContrailColor',
  'engineGlowLengthMult',
  'engineGlowWidthMult',
  'engineGlowGlowMult',
  'weaponGlowColor',
  'weaponTypes',
  'jitterColor',
  'jitterCopies',
  'jitterMinRange',
  'jitterRange',
  'jitterRangeRadiusFraction',
  'jitterUnderColor',
  'jitterUnderCopies',
  'jitterUnderMinRange',
  'jitterUnderRange',
  'jitterUnderRangeRadiusFraction',
  'effectColor1',
  'effectColor2',
  'phaseHighlight',
  'phaseDiffuse',
  'shipAlpha',
  'shieldRingColor',
  'shieldInnerColor',
  'shieldThicknessMult',
  'shieldFluctuationMult',
  'range',
  'randomRange',
  'renderCopyDuringTeleport',
  'weaponDataId',
  'droneVariant',
  'allowFreeRoam',
  'launchSpeed',
  'launchDelay',
  'maxDrones',
  'droneBehavior',
  'empDamage',
  'damage',
  'damageType',
  'aiHints',
]);

/// Fields exclusive to one system type; they are stripped from the spec when
/// the type changes away so stale engine/shield/phase data never survives.
export const TYPE_EXCLUSIVE_FIELDS: Record<string, readonly string[]> = {
  ENGINE_MOD: [
    'engineGlowColor',
    'engineGlowContrailColor',
    'engineGlowLengthMult',
    'engineGlowWidthMult',
    'engineGlowGlowMult',
    'flameoutOnImpactChance',
    'alwaysAccelerate',
  ],
  SHIELD_MOD: ['shieldRingColor', 'shieldInnerColor', 'shieldThicknessMult', 'shieldFluctuationMult'],
  PHASE_CLOAK: ['effectColor1', 'effectColor2', 'phaseHighlight', 'phaseDiffuse', 'shipAlpha'],
  DISPLACER: ['range', 'randomRange', 'renderCopyDuringTeleport'],
  WEAPON: ['weaponDataId'],
  DRONE_LAUNCHER: ['droneVariant', 'allowFreeRoam', 'launchSpeed', 'launchDelay', 'maxDrones', 'droneBehavior'],
};
